apiVersion: v1
kind: Service
metadata:
  name: api-python
  labels:
    app: api-python
spec:
  type: ClusterIP
  selector:
    app: api-python
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
