name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build imagem Docker
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push imagem
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy com Helm
        run: |
          helm upgrade --install api-python ./charts/api-python \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=latest
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
