name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build imagem Docker
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push imagem
        run: docker push ghcr.io/${{ github.repository }}:latest
      
      - name: Setup Kind cluster
        uses: helm/kind-action@v1.6.0

      - name: Instalar o Helm
        uses: azure/setup-helm@v3

      - name: Verificar se o cluster Kind está acessível
        run: kubectl cluster-info

      - name: Deploy com Helm no Kind
        run: |
          helm upgrade --install api-python ./charts/api-python \
            --namespace demo \
            --create-namespace \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=latest \
            --set image.pullPolicy=IfNotPresent

      - name: Esperar pod ficar pronto
        run: kubectl rollout status deployment api-python -n demo

      - name: Testar endpoint local
        run: |
          kubectl port-forward svc/api-python 8080:8080 -n demo &
          sleep 5
          curl http://localhost:8080


